### ISSUE TITLE
Bot doesn't do anything and then errors if you try play without anything

### ISSUE THREAD

**Issue by blubaustin** [romainisnel/hertz#18] opened 2018-11-14 01:49 UTC
Bot launches won't respond to any commands but if you do play without any options it will error out with this error:
main.commandHandler(0xc420095440, 0xc42000e980)
        /home/blubaustin/hertz/main.go:119 +0xa39
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x7ee420, 0xc420095440, 0x76c020, 0xc42000e980)
        /home/blubaustin/src/github.com/bwmarrin/discordgo/eventhandlers.go:496 +0x57
created by github.com/bwmarrin/discordgo.(*Session).handle
        /home/blubaustin/src/github.com/bwmarrin/discordgo/event.go:162 +0x114
![image](https://user-images.githubusercontent.com/31782440/48454566-e80a1e80-e774-11e8-81ad-86e8a14fd2be.png)

**Comment by romainisnel** [comment] 2018-11-14 08:37
Thanks for the feedback @blubaustin.

The index out of range error is cause by the fact that there is no second parameter in the command you are passing to the bot. This is poor quality code I must say, and will be fixed.

When you say the bot doesn't do anything, can you tell me what you are trying to do and what fails. The more detailed your explanation, the faster the issue will be resolved. If you can describe your process, this would greatly help me, thanks.

**Comment by romainisnel** [comment] 2018-11-15 17:48
Did you give the permissions to the bot ? Also, the command to play youtube videos is *youtube* not *play*, the *play* command only plays mp3 files.

**Comment by blubaustin** [comment] 2018-11-16 05:10
Yes it has permissions to play. I can try the youtube command.

**Comment by romainisnel** [comment] 2018-11-16 13:16
I'm trying to reproduce the bug on my side. I'll get back to you if I make progress on this.

**Comment by romainisnel** [comment] 2018-11-19 10:57
I was not able to reproduce this behavior @blubaustin. 
Can you tell me more about the environment the bot is running in ?
I'll leave the issue open, tell me if you find anything.

**Comment by blubaustin** [comment] 2018-11-19 16:06
It is running on the latest version of debian, on a VPS, what other info do you want me to provide?

**Comment by romainisnel** [comment] 2018-11-20 12:17
It might be a problem with the linux version of **go-opus**, I'll make some test.

Can you tell me what version of Go you are using ?

**Comment by blubaustin** [comment] 2018-11-21 05:44
Go 1.9.4

**Comment by romainisnel** [comment] 2018-12-10 07:51
I wasn't able to reproduce this. I'll close the issue due to inactivity.

**Closed** 2018-12-10 07:51 UTC
Labels: bug, help wanted
